columnSuffix: null
contentColumnType: string
fieldGroup: 069dc2f7-14d2-4253-aba3-1b113b1de6f8 # Sneakers
handle: sneakers
instructions: null
name: Sneakers
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:92e9a5a9-69e9-42de-9eef-c38bbdc41e59' # Sneakers
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:92e9a5a9-69e9-42de-9eef-c38bbdc41e59' # Sneakers
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'add sneakers image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:92e9a5a9-69e9-42de-9eef-c38bbdc41e59' # Sneakers
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
